---
- name: sample playbook
  hosts: webserver
  tasks:
  - name: sample file
    file:
      name: sample.txt
      path: /tmp/
      owner: root
      group: root
      mode: 0644
      state: touch
  - name: install apache2
    apt: pkg=apache2 state=present
  - name: start apache2 service
    service:
      name: apache2
      state: started